services:
  - type: web
    name: healthguard-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python launch_system.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
    healthCheckPath: /health
    autoDeploy: true
